---
pt-PT:
  admin:
    custom_emojis:
      batch_copy_error: 'Houve um erro ao copiar alguns dos emoji selecionados: %{message}'
      batch_error: 'Houve um erro: %{message}'
    domain_allows:
      export: Exportar
      import: Importar
    domain_blocks:
      export: Exportar
      import: Importar
    export_domain_allows:
      new:
        title: Importar domínios permitidos
      no_file: Nenhum ficheiro seleccionado
    export_domain_blocks:
      import:
        description_html: Estás prestes a importar uma lista de bloqueios de domínios. Revê essa lista com cuidado, especialmente se não foste tu a criá-la.
        existing_relationships_warning: Relações de seguidores existentes
        private_comment_description_html: 'Para te ajudar a seguir de onde vêm os bloqueios importados, cada bloqueio importado vai ser criado com um comentário privado: <q>%{comment}</q>'
        private_comment_template: Importado de %{source} em %{date}
        title: Importar bloqueios de domínio
      new:
        title: Importar bloqueios de domínio
      no_file: Nenhum ficheiro seleccionado
    settings:
      captcha_enabled:
        desc_html: Isto depende de scripts externos da hCaptcha, o que pode ser uma preocupação de segurança e privacidade. Além disso, <strong>isto pode tornar o processo de registo menos acessível para algumas pessoas (especialmente as com limitações físicas)</strong>. Por isto, considera medidas alternativas tais como registo mediante aprovação ou sob convite.<br>Pessoas que se registam com um convite não precisam de resolver um CAPTCHA
        title: Exigir que novas contas resolvam um CAPTCHA para validar o registo
      flavour_and_skin:
        title: Sabor e tema
      hide_followers_count:
        desc_html: Não mostrar o número de seguidores nos perfis
        title: Esconder o número de seguidores
      other:
        preamble: Várias opções do glitch-soc que não cabem noutras categorias.
        title: Outras opções
      outgoing_spoilers:
        desc_html: Ao federar toots, juntar este aviso de conteúdo aos toots que não têm aviso. Isto é útil se o teu servidor for especializado em conteúdos que outros servidores podem querer ter sob um Aviso de Conteúdo. Os media também vão ser marcados como sensíveis.
        title: Aviso de conteúdo para toots enviados
      show_reblogs_in_public_timelines:
        desc_html: Mostrar boosts públicos de toots públicos nas linhas de tempo locais e públicas.
        title: Mostrar boosts nas timelines públicas
      show_replies_in_public_timelines:
        desc_html: Além de auto-respostas públicas (fios), mostrar as respostas públicas em linhas de tempo locais e públicas.
        title: Mostrar respostas nas linhas de tempo públicas
      trending_status_cw:
        desc_html: Quando os posts em tendência estão ativados, permitir que posts com Avisos de Conteúdo também possam aparecer. As alterações nesta opção não são retroativas.
        title: Permitir que posts com Avisos de Conteúdo possam aparecer nos posts em tendência
  appearance:
    localization:
      glitch_guide_link: https://crowdin.com/project/glitch-soc
      glitch_guide_link_text: E também para o glitch-soc!
  auth:
    captcha_confirmation:
      hint_html: Só mais um passo! Para confirmares a tua conta, este servidor exige que resolvas um CAPTCHA. Podes <a href="/about/more">entrar em contacto com o administrador do servidor</a> se tiveres dúvidas ou precisares de ajuda.
      title: Verificação
  compose_form:
    spoiler: Esconder o texto por trás de um aviso de conteúdo
  generic:
    use_this: Usar isto
  settings:
    flavours: Temas do interface
